### ISSUE TITLE
css-modules 好像无法兼容style["class-name"]

### ISSUE THREAD

**Issue by lettywiterock** [alitajs/umi-plugins#5]
使用style["class-name"]这种方式，好像无法被解析

**Comment by xiaohuoni** [comment]
style["class-name"]这种方式 -- 这是什么方式？

**Comment by lettywiterock** [comment]
className={style.classname}  如果class命名"class-name"这种怎么办
之前用style['class-name']可以取出

**Comment by xiaohuoni** [comment]
这个问题，为什么发在这里？使用了什么插件之后不行吗？

**Comment by wangxingkang** [comment]
我看下

**Comment by wangxingkang** [comment]
我试了下 是可以的 请提供最小可复现仓库

**Comment by wangxingkang** [comment]
可以试一下 https://github.com/alitajs/umi-plugin-packages/blob/master/examples/umi-plugin-css-modules 这块的示例

**Comment by lettywiterock** [comment]
抱歉没网不能拍照
//index. less
.table-component{
   background-color:#000;
}
//index.js

..... 
import styles from "./index.less";
render(){
   return(
        <div id="table-test"  className={styles["table-component"]}>TableCom</div>
   )
}
用的是js编辑，没用ts
umi配置是默认的，没有cssModule方面的修改。
以上手打，单纯的string可以识别，对象也可以，唯独这个对象key的不能。
造成效果是，在页面上dom节点只有id，class没有被解析，直接没有class这项

**Comment by lettywiterock** [comment]
config. module. rule(rule). use("css-loader"). tap(options=>Object.assign(options,{modules:false}))
这个关闭了css的，开启之后支持styles["class-name"]但是会导致，不支持className="class-name"
false关闭之后，不支持style["class-name"]

**Comment by lettywiterock** [comment]
{
 "dependencies":{
 "@alitajs/umi-plugin-css-modules":"0.0.2",
"react":"^16.8.6",
"react-dom":"^16.8.6"
},
{
  "devDependencies":{
   "umi":"^2.7.7",
  "umi-plugin-react":"^1.8.4"
}
}

}

**Comment by lettywiterock** [comment]
> {
> "dependencies":{
> "@alitajs/umi-plugin-css-modules":"0.0.2",
> "react":"^16.8.6",
> "react-dom":"^16.8.6"
> },
> {
> "devDependencies":{
> "umi":"^2.7.7",
> "umi-plugin-react":"^1.8.4"
> }
> }
> 
> }

**Comment by lettywiterock** [comment]
@wangxingkang 就这个简单配置

**Comment by wangxingkang** [comment]
需要使用 .module.less  .module.css  需要使用后缀

**Comment by wangxingkang** [comment]
可以加入下 21924668  alita钉钉群

**Comment by wangxingkang** [comment]
@alitajs/umi-plugin-css-modules 放在devDependencies 比较合适

**Comment by lettywiterock** [comment]
thankyou好了，果然需要添加别名。
感谢(❁´ω`❁)
